language: rust
rust:
- stable
- beta
- nightly
cache: cargo
before_script:
- rustup component add rustfmt
script:
- cargo fmt --all -- --check
- cargo build
- cargo test
env:
  global:
  - secure: v97QkUfM0EBBGaNVdZMtJujDXq72mlew5D0YjNC4ayqa2RbPbUPMI3LmYoJEbO7MfgMhN/ZQ8X+BBulIN0wrg0gXR4q99hcdri1g6fUGu0F09jzzm92zMV+bF7n7uFvmetORwXlqu2yEtxM9kxE7OfNj1wMODc5AordB7C3yJNPMeEYJ2q/R+d/q8Em7Xwxw1+EzRZ4JDsxDe5vwtxpJ87pGb8HoYbEd/aet1a/6laSlyAnwXYO0X8oO2m1egwA9i7kkCcJavF0NJPYtuU/2NkPhNZJmWP68BtbkXIjegO1XGKQbEFgGN2JeryJLl803N3jvk5I9T2JDZ2M9S9ZDyFzof2qwqSU7Ee0cN2KDR05+hpwYoiHLooMB0AEPMTREagUdR7Ndr+2irlNHN+HRdSXcStw/3ZP4nVHgpRXVlPlpa9jHAmG4jhbR2p1BuqoXbPnY1q6Xn0AEyQ9czclsIkuiVqmxf46SPM2jXcEdm2eY/ksw9BkyIu4DrWvN/D3lsVsK5iIYuhGbrqVMRaBNEqCGAtQpaZ1mM7HwawEw6MASIpWaT2cZbkCJ0inMRLplf1Vz3HgZZScR9oAOhZMJ2aRopbghChkPAW/W5iEMspDrUJv+tJ87meur/ZkW5xkxFvrw/dEXZ/ppF5rbGVCWe/zRHO0+Bejsc7s7e2LdQOU=
